update Deprecated Domain
userbradley/BeReal pull request #7
Opened 2023-03-04 21:14 UTC by max21910

this domain is not use anymore by Bereal it was removed (can't say why for privacy reason )

2023-03-05 12:28 UTC, max21910 commented
add memories  video link

2023-03-07 12:14 UTC, userbradley requested changes
Thanks for another PR!

The markdown table does not seem to be formatted correctly. Are you able to fix it?

2023-03-07 12:14 UTC, userbradley commented on README.md
> +| `https://bereal-us-central1-memories.storage.googleapis.com ` | Memories recap video storage
This does not appear to be formatted correctly!

Are you able to change it?

2023-03-19 22:38 UTC, max21910 reviewed
hi i refformated the file sorry for the delay !

2023-05-01 17:52 UTC, closed without merging

2023-05-02 09:49 UTC, userbradley commented
Ah sorry @max21910 - If you want to re-open it I'll merge this. For some reason I was not getting notifications from this